# Generated by Django 3.1.4 on 2021-07-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_user',
            name='fullname',
            field=models.CharField(default=1, max_length=60, verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
