# Generated by Django 3.1.4 on 2021-07-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20210729_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_user',
            name='email',
            field=models.CharField(default='2', max_length=20, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='shop_user',
            name='mobile',
            field=models.CharField(default='1', max_length=20, verbose_name='手机号'),
        ),
    ]
