# Generated by Django 3.1.4 on 2021-07-31 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_shop_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50, verbose_name='菜单名')),
                ('is_delete', models.IntegerField(default=0, verbose_name='是否删除：0-未删 1-已删')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '一级菜单表',
                'verbose_name_plural': '一级菜单表',
            },
        ),
        migrations.CreateModel(
            name='submenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submenu_name', models.CharField(max_length=50, verbose_name='子菜单名')),
                ('submenu_route', models.CharField(max_length=50, verbose_name='子页面路由')),
                ('is_delete', models.IntegerField(default=0, verbose_name='是否删除：0-未删 1-已删')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.menu', verbose_name='父菜单id')),
            ],
            options={
                'verbose_name': '子菜单',
                'verbose_name_plural': '子菜单',
            },
        ),
    ]
