# Generated by Django 3.1.4 on 2021-07-31 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_menu_submenu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_name',
            new_name='menuName',
        ),
        migrations.AlterField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='first.menu', verbose_name='父菜单id'),
        ),
    ]
