# Generated by Django 3.1.4 on 2021-07-31 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20210731_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submenu',
            old_name='submenu_route',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='submenu',
            old_name='submenu_name',
            new_name='subName',
        ),
    ]
